### PR TITLE
Saving feature

### PR DESCRIPTION
**Pull request by dluciv**
Saving `bookmarks.data`

### CODE REVIEW

**Comment by skx** [comment]
Initial glance it looks reasonable, but it definitely needs a section adding to the `README.md` file demonstrating how to use it.

That was the problem I had in the past, I didn't test it because when I tried to use it it didn't work.

**Comment by dluciv** [comment]
Wrote few lines to `README.md`.

> That was the problem I had in the past, I didn't test it because when I tried to use it it didn't work.

Not sure I understood you right. I haven't suggested any changes related to saving data in the past. My recent changes work for me, but I will be glad to improve them if anything bad happens to saved data...

**Comment by skx** [comment]
Sorry for confusing you :)

I meant in the past, not in this code.  It looks good.  WIll test tonight before merging.

**Comment by dluciv** [comment]
Okay, thank you!

**Pull request merged**
